# Generated by Django 4.1.7 on 2023-03-29 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='timstamp',
            new_name='timestamp',
        ),
    ]
